baseURL = 'https://example.org/'
languageCode = 'en-us'
defaultContentLanguage = 'en-us'
title = 'typo-marko'

# Default config
[params.breadcrumbs]
enabled = true
showCurrentPage = true
home = "Home"