name = 'typo-marko'
license = 'Unlicense'
licenselink = 'https://github.com/markop404/typo-marko/blob/main/LICENSE.txt'
description = 'Fork of the typo theme for Hugo'
homepage = 'https://github.com/markop404/typo-marko/'
demosite = 'https://markopejic.com'
tags = [
    "responsive",
    "simple",
    "clean",
    "light",
    "dark",
    "blog",
    "minimal",
    "personal",
    "portfolio",
]

features = [
    "responsive",
    "blog",
    "table-of-contents",
    "highlight.js",
    "social-icons",
    "minified-assets",
    "dark-light-images",
    "color-palettes",
]

[author]
name = 'Marko Pejić'
homepage = 'https://markopejic.com'
